server {
    listen 80;
    root /usr/share/nginx/html;

    # htmls of Potree
    location /potree/ {
        alias /usr/share/nginx/potree/;
        # index index.html;
        autoindex on;
    }

    # fallback: 404
    location / {
        return 404;
    }
}