server {
    listen 443 ssl;
    server_name <your host ip or domain>;

    # ssl settings
    ssl_certificate     /etc/nginx/conf.d/server.crt;
    ssl_certificate_key /etc/nginx/conf.d/server.key;

    # Redirect HTTP requests to HTTPS
    error_page 497 https://$host:9999$request_uri;

    # basic auth settings
    auth_basic "Restricted Potree Data";
    auth_basic_user_file /etc/nginx/.htpasswd;

    # location settings
    root /usr/share/nginx/html;

    # htmls of Potree
    location /potree/ {
        alias /usr/share/nginx/potree/;
        # index index.html;
        autoindex off;
    }

    location /potree/_page/ {
        alias /usr/share/nginx/potree/_page/;
        # index index.html;
        autoindex on;
    }

    location /potree/_data/ {
        alias /usr/share/nginx/potree/_data/;
        # index index.html;
        autoindex off;
    }

    # fallback: 404
    location / {
        return 404;
    }
}
