server {
    listen 80;
    root /usr/share/nginx/html;

    # htmls of Potree
    location /potree/ {
        alias /usr/share/nginx/potree/;
        # index index.html;
        autoindex off;
    }

    location /potree/examples/ {
        alias /usr/share/nginx/potree/examples/;
        # index index.html;
        autoindex on;
    }

    location /potree/meidai/ {
        alias /usr/share/nginx/potree/meidai/;
        # index index.html;
        autoindex on;
    }

#    location /potree/trusco/ {
#        alias /usr/share/nginx/potree/trusco/;
# 	    #index index.html;
#        autoindex on;
#    }

    # fallback: 404
    location / {
        return 404;
    }
}
